name: Code Review

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  code-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Code Review GPT
        uses: mattzcarey/code-review-gpt@v0.1.10
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
